version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # Database Configuration
      - DATABASE_URL=sqlite:///./app.db
      
      # JWT Configuration
      - SECRET_KEY=production-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=true
      
      # CORS Configuration
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 